<?php

namespace TomJerryBundle\Repository;

/**
 * GalaryImagesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GalaryImagesRepository extends \Doctrine\ORM\EntityRepository
{
}
