security:
    encoders:
        AkjnBundle\Entity\User:
            id: security.encoder.securedlogin
    role_hierarchy:
        ROLE_TMJR_USER: [ROLE_TMJR_USER]
        ROLE_TMJR_ADMIN: [ROLE_TMJR_ADMIN]
        ROLE_TMJR_SUPERUSER: [ROLE_TMJR_USER, ROLE_TMJR_ADMIN, ROLE_TMJR_SUPERUSER]

    providers:
        fos_userbundle:
                id: fos_user.user_provider.username_email
    firewalls:
        main:
            pattern: ^/
            simple-form:
                provider:      fos_userbundle
                authenticator: security.authenticator.securedlogin
                login_path:    /login
                csrf_provider: form.csrf_provider
                use_forward:   true
                
                # login success redirecting options (read further below)
                always_use_default_target_path: false
                default_target_path: /
                target_path_parameter: _target_path
                use_referer: false
                
                check_path:    /security/login_check
                success_handler: akjn.security.handler.login_success_handler
                failure_handler: akjn.security.handler.login_failure_handler
                failure_path:   /
                
                username_parameter: _peru
                password_parameter: _thakol
                
            logout:
                path:   /prelogout
                target: /
                success_handler: akjn.security.handler.logout_success_handler
            anonymous:   true

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/fyfi/, roles: [ROLE_FYFI_USER, ROLE_FYFI_ADMIN, ROLE_SUPER_ADMIN] }
#        - { path: ^/schm/, roles: [ROLE_FYFI_USER, ROLE_FYFI_ADMIN, ROLE_SUPER_ADMIN] }