tom_jerry_homepage:
    path:     /
    defaults: { _controller: TomJerryBundle:Default:index }
    
home_page:
    path:     /
    defaults: { _controller: TomJerryBundle:Default:index }

admin_route:
    resource: "adminRoute.yml"
    prefix: /admin